twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        # All globals variables here
        localeList: '@App\Service\LocalesManager'
when@test:
    twig:
        strict_variables: true
