homepage:
  path:
    en: '/en'
    fr: '/'
  defaults:
    _controller: App\Controller\HomepageController::index
    _locale: '%locale%'
  requirements:
    _locale: '%app_locales%'

login:
  path:
    en: '/login'
    fr: '/connexion'
  defaults:
    _controller: App\Controller\LoginController::index
    _locale: '%locale%'
  requirements:
    _locale: '%app_locales%'

register:
  path:
    en: '/register'
    fr: '/inscription'
  defaults:
    _controller: App\Controller\RegistrationController::register
    _locale: '%locale%'
  requirements:
    _locale: '%app_locales%'

app_logout:
  path: /logout
  methods: GET
